version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - thenativeweb/internal_eventsourcingdb_dep
  labels:
  - Dependencies
  allow:
  - dependency-type: direct
  commit-message:
    prefix: chore
    prefix-development: chore

- package-ecosystem: docker
  directory: "/docker/eventsourcingdb"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  assignees:
  - thenativeweb/internal_eventsourcingdb_dep
  labels:
  - Dependencies
  commit-message:
    prefix: chore

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  assignees:
  - thenativeweb/internal_eventsourcingdb_dep
  labels:
  - Dependencies
  commit-message:
    prefix: chore
