name: QA

on: pull_request

concurrency:
  group: qa-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Clone repository
      uses: actions/checkout@v5
    - name: Use Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
    - name: Run QA
      run: make qa
