name: QA

on: pull_request

permissions:
  contents: read
  packages: read

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Configure access to private Go dependencies
      run: |
        echo "machine github.com login goloroden password ${{ secrets.TOKEN_GITHUB_TO_GITHUB_REPOSITORIES_RW }}" >> ~/.netrc
    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod
    - name: Run QA
      run: make qa
