name: QA

on: pull_request

permissions:
  contents: read
  packages: read

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Login to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_ACCESS_TOKEN }}
    - name: Use Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Run QA
      run: make qa
