name: Release

on:
  push:
    branches:
      - 'main'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        token: ${{ env.GH_TOKEN }}
    - name: Login to GitHub container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: goloroden
        password: ${{ secrets.GHCR_ACCESS_TOKEN }}
    - name: Use Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Run QA
      run: make qa
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@2.0.0
    - name: Create new version
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        git tag ${{steps.get_next_version.outputs.version}}
        git push origin ${{steps.get_next_version.outputs.version}}
