name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Configure access to private Go dependencies
      run: |
        echo "machine github.com login goloroden password ${{ secrets.TOKEN_GITHUB_TO_GITHUB_REPOSITORIES_RW }}" >> ~/.netrc
    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
    - name: Run QA
      run: make qa
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@2.5.0
    - name: Create new version
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        git tag v${{steps.get_next_version.outputs.version}}
        git push origin v${{steps.get_next_version.outputs.version}}
